### PR TITLE
Fix issue 139

### PR DESCRIPTION
**Pull request by ali-abz**
Add sanity check for `validatefreq < niters`
Add log message for validation schedule

### CODE REVIEW

**Comment by andrewyates** [comment]
Looks good to me. Could you also add a check and message to the [Tensorflow trainer](https://github.com/capreolus-ir/capreolus/blob/master/capreolus/trainer/tensorflow.py)? I think this should only require similar changes around lines 99 and 220. I can handle it myself if TF is difficult to test on your end though.

**Comment by ali-abz** [comment]
I'll do my best.

**Comment by ali-abz** [comment]
Hi Andrew,
I've been trying to add the log message for tensorflow trainer but I have failed to test it since the only models that make use of tensorflow are bert-based models and currently, I don't have a proper hardware that can manage them.

**Comment by andrewyates** [comment]
No worries, I can try it soon then. Thanks a lot for helping with this

**Comment by ali-abz** [comment]
It's been my pleasure.

**Pull request merged**
