### PR TITLE
Check covid

### PR DESCRIPTION
**Pull request by crystina-z**
1. previous error was because when `useprevqrels` (i.e. `excluseknown`) set to False, the empty qids are stored in folds["train_qids"] and folds["predict"]["dev"]
2. a lot of renaming XP (yeah the previous naming was too confusing that it takes even me myself a long while to understand what's happening..)
3. did a quick pass for round3, the score seems compatible with anserini results. but my first trials on round4 does not. Trying to find out the reason for that.

sample script to get round3 result:
```
python run.py rank.search with \
        benchmark.name=covid benchmark.collection.name=covid \
        filter=True  searcher.name=BM25Postprocess \
        searcher.fields=query+question searcher.k1=0.5,0.6,0.7,0.8,0.9,1.0,1.1 searcher.b=0.3,0.4,0.5,0.6 \
        benchmark.useprevqrels=True benchmark.udelqexpand=True \
        benchmark.collection.round=3
```

### CODE REVIEW

**Comment by crystina-z** [comment]
current scores (using qrels at current run), obtained using the scripts [here](https://gist.github.com/crystina-z/d74d3cf6014528756fb16f612569ae99). The anserini results are from [here](https://github.com/castorini/anserini/blob/master/docs/experiments-covid.md).

**_round 4_**
|          |        index |    field(s)    |   | expected |        |        |   |   got   |        |        |
|----------|:------------:|:--------------:|:-:|:--------:|:------:|:------:|:-:|:-------:|:------:|:------:|
|   |        |       |   | nDCG@10  | J@10   | R@1k   |   | nDCG@10 | J@10   | R@1k   |
| 1 | abstract     | query+question |   | 0.3143   | 0.4467 | 0.4257 |   | 0.3249  | 0.5025 | 0.4349 |
| 2 | abstract     | UDel   qgen    |   | 0.326    | 0.4378 | 0.4432 |   | 0.3169  | 0.5175 | 0.4501 |
| 3 | full-text    | query+question |   | 0.2108   | 0.4044 | 0.3891 |   | 0.2337  | 0.485  | 0.4293 |
| 4 | full-text    | UDel   qgen    |   | 0.3499   | 0.5067 | 0.4537 |   | 0.3733  | 0.58   | 0.4719 |
| 5 | paragraph    | query+question |   | 0.3229   | 0.5267 | 0.4863 |   | **0.3168**  | 0.575  | 0.4942 |
| 6 | paragraph    | UDel   qgen    |   | 0.4016   | 0.5333 | 0.505  |   | 0.4056  | 0.5925 | 0.5076 |

**_round 3_**
|          |        index |    field(s)    |   | expected |        |        |   |   got   |        |        |
|----------|:------------:|:--------------:|:-:|:--------:|:------:|:------:|:-:|:-------:|:------:|:------:|
|          |              |                |   | nDCG@10  | J@10   | R@1k   |   | nDCG@10 | J@10   | R@1k   |
| 1       | abstract     | query+question |   | 0.2118   | 0.33   | 0.4398 |   | 0.2149  | 0.3743 | 0.4412 |
| 2        | abstract     | UDel   qgen    |   | 0.247    | 0.3375 | 0.4537 |   | 0.2507  | 0.3914 | 0.4536 |
| 3        | full-text    | query+question |   | 0.2337   | 0.465  | 0.4817 |   | 0.2369  | 0.52   | 0.5081 |
| 4        | full-text    | UDel   qgen    |   | 0.343    | 0.5025 | 0.5267 |   | 0.3443  | 0.5886 | 0.5415 |
| 5        | paragraph    | query+question |   | 0.2848   | 0.5175 | 0.5527 |   | 0.2944  | 0.5914 | 0.5553 |
| 6        | paragraph    | UDel   qgen    |   | 0.3604   | 0.505  | 0.5676 |   | **0.3482**  | 0.5771 | 0.5731 |

**_round 2_**
|              |   index   |    field(s)    |   | expected |        |        |   |   got   |        |        |
|--------------|:---------:|:--------------:|:-:|:--------:|:------:|:------:|:-:|:-------:|:------:|:------:|
|              |           |                |   | nDCG@10  | J@10   | R@1k   |   | nDCG@10 | J@10   | R@1k   |
| 1            | abstract  | query+question |   | 0.3522   | 0.5371 | 0.6601 |   | 0.3571  | 0.64   | 0.6637 |
| 2            | abstract  | UDel   qgen    |   | 0.3781   | 0.5371 | 0.6485 |   | **0.3395**  | 0.62   | 0.6494 |
| 3            | full-text | query+question |   | 0.207    | 0.4286 | 0.5953 |   | 0.2476  | 0.5067 | 0.6294 |
| 4            | full-text | UDel   qgen    |   | 0.3123   | 0.4229 | 0.6517 |   | 0.3353  | 0.5    | 0.6637 |
| 5            | paragraph | query+question |   | 0.2772   | 0.44   | 0.7248 |   | 0.2695  | 0.5267 | 0.7314 |
| 6            | paragraph | UDel   qgen    |   | 0.3353   | 0.4343 | 0.7196 |   | 0.3451  | 0.54   | 0.7285 |

**Comment by crystina-z** [comment]
did another test on round 3 with `qrels.covid-round3-cumulative.txt`, yet this cannot be directly produced by this code: since  for this result anserini does not exclude judgment from previous runs, need to move the contents in `benchmark.qrels_ignore` to `benchmark.qrels` before evaluation to obtain this result:

|   |      index     |  fields              |   | expected |        |        |   |   got   |        |        |
|---|-----------|----------------|---|:--------:|:------:|:------:|:-:|:-------:|:------:|:------:|
|   |           |                |   | nDCG@10  | J@10   | R@1k   |   | nDCG@10 | J@10   | R@1k   |
| 1 | abstract  | query+question |   | 0.5781   | 0.8875 | 0.504  |   | 0.5797  | 0.88   | 0.5005 |
| 2 | abstract  | UDel   qgen    |   | 0.6291   | 0.93   | 0.5215 |   | 0.623   | 0.9175 | 0.517  |
| 3 | full-text | query+question |   | 0.3977   | 0.75   | 0.4708 |   | 0.4118  | 0.7725 | 0.5084 |
| 4 | full-text | UDel   qgen    |   | 0.579    | 0.905  | 0.5313 |   | 0.598   | 0.9325 | 0.5551 |
| 5 | paragraph | query+question |   | 0.5396   | 0.9425 | 0.5766 |   | 0.5538  | 0.94   | 0.5792 |
| 6 | paragraph | UDel   qgen    |   | 0.6327   | 0.96   | 0.5923 |   | 0.6302  | 0.9525 | 0.5927 |

**Comment by andrewyates** [comment]
Can this be merged?

**Comment by crystina-z** [comment]
> Looks fine to me. Do you have any idea why the evaluation results are slightly different from Anserini's though? Is it the evaluation code or a difference in the run itself?

ah I didn't see this, the possible reasons came first to me are that 
(1) `k1` and `b` is tuned here yet not anserini -> will run default BM25 later
(2) instead of using the covid topic reader, we transform it into trec file, not sure if that would make any difference

> Can this be merged?

other than this (mild?) mismatch I don't see other problems. If it's necessary, maybe I can come back to this after the ddl?

**Pull request merged**
